
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

some_password: welcome
latitude_coord: 48.791219
longitude_coord: 44.589135

api_key_bot: 5150327368:AAHH2z9xk_k1hrMctNXDPK89M_9AUAAJkQM

telegram_id_1: 1166777449
telegram_id_2: -1001846355321
#telegram_id_2: -643617984
room25_token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyY2QxMTRlOTY2OWY0NjU1OTFiOTEwN2QzYTBlYzY5ZCIsImlhdCI6MTY3NjkyMDYxMSwiZXhwIjoxOTkyMjgwNjExfQ.3kjvUoUB4gc964fI14SZMtpNlwBOWepH1P8aAb1JnAs
